export const ADD_MEALS = 'ADD_MEALS';
export const MEALS_LOADING = 'MEALS_LOADING';
export const MEALS_FAILED = 'MEALS_FAILED';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const FILTER_CATEGORY = 'FILTER_CATEGORY';